package com.typepiano.reference;

public class Note {
	
	public final static String C1 = MusicFile.a1;
	public final static String D3 = MusicFile.a2;
	public final static String E5 = MusicFile.a3;
	public final static String F6 = MusicFile.a4;
	public final static String G8 = MusicFile.a5;
	public final static String A10 = MusicFile.a6;
	public final static String B12 = MusicFile.a7;
	public final static String C13 = MusicFile.a8;
	public final static String D15 = MusicFile.a9;
	public final static String E17 = MusicFile.a10;
	public final static String F18 = MusicFile.a11;
	public final static String G20 = MusicFile.a12;
	public final static String A22 = MusicFile.a13;
	public final static String B24 = MusicFile.a14;
	public final static String C25 = MusicFile.a15;
	public final static String D27 = MusicFile.a16;
	public final static String E29 = MusicFile.a17;
	public final static String F30 = MusicFile.a18;
	public final static String G32 = MusicFile.a19;
	public final static String A34 = MusicFile.a20;
	public final static String B36 = MusicFile.a21;
	public final static String C37 = MusicFile.a22;
	public final static String D39 = MusicFile.a23;
	public final static String E41 = MusicFile.a24;
	public final static String F42 = MusicFile.a25;
	public final static String G44 = MusicFile.a26;
	public final static String A46 = MusicFile.a27;
	public final static String B48 = MusicFile.a28;
	public final static String C49 = MusicFile.a29;
	public final static String D51 = MusicFile.a30;
	public final static String E53 = MusicFile.a31;
	public final static String F54 = MusicFile.a32;
	public final static String G56 = MusicFile.a33;
	public final static String A58 = MusicFile.a34;
	public final static String B60 = MusicFile.a35;
	public final static String C61 = MusicFile.a36;
	
	public final static String Cx2 = MusicFile.b1;
	public final static String Dx4 = MusicFile.b2;
	public final static String Fx7 = MusicFile.b3;
	public final static String Gx9 = MusicFile.b4;
	public final static String Ax11 = MusicFile.b5;
	public final static String Cx14 = MusicFile.b6;
	public final static String Dx16 = MusicFile.b7;
	public final static String Fx19 = MusicFile.b8;
	public final static String Gx21 = MusicFile.b9;
	public final static String Ax23 = MusicFile.b10;
	public final static String Cx26 = MusicFile.b11;
	public final static String Dx28 = MusicFile.b12;
	public final static String Fx31 = MusicFile.b13;
	public final static String Gx33 = MusicFile.b14;
	public final static String Ax35 = MusicFile.b15;
	public final static String Cx38 = MusicFile.b16;
	public final static String Dx40 = MusicFile.b17;
	public final static String Fx43 = MusicFile.b18;
	public final static String Gx45 = MusicFile.b19;
	public final static String Ax47 = MusicFile.b20;
	public final static String Cx50 = MusicFile.b21;
	public final static String Dx52 = MusicFile.b22;
	public final static String Fx55 = MusicFile.b23;
	public final static String Gx57 = MusicFile.b24;
	public final static String Ax59 = MusicFile.b25;
}
